### PR TITLE
separated resultError and resultErrorEntity

### LINKED ISSUE #4: Error handling
Need a case for Exception

### PR DESCRIPTION
**Pull request by peteryu24**
separated resultError and resultErrorEntity

### CODE REVIEW

File: src/main/java/waterMill/WaterMillController.java [hunk 1]
```diff
@@ -26,12 +26,12 @@ public WaterMillResult setForCalculation(@Valid int monthlyAmount, int endPeriod
 
 	@ExceptionHandler(IllegalArgumentException.class)
 	public WaterMillResult IllegalArgumentException(IllegalArgumentException exception) {
-		return waterMillResult.resultError("IllegalArgumentException",
+		return waterMillResult.resultErrorEntity("IllegalArgumentException",
```
Comment (peteryu24) [inline src/main/java/waterMill/WaterMillController.java:29]: Entity resolved to handle better and more efficiently
